CREATE TABLE INQUILINO (
    NIF number(8) PRIMARY KEY,
    NOMBRE varchar2(255) NOT NULL,
    APELLIDOS varchar2(255) NOT NULL,
    NACIMIENTO date NOT NULL
);

CREATE TABLE EDIFICIO (
    ID_EDIFICIO number(8) PRIMARY KEY,
    CALLE varchar2(25) NOT NULL,
    NUMERO number(8) NOT NULL,
    POBLACION varchar2(25) NOT NULL,
    N_PISOS number(8) NOT NULL,
    N_GARAJES number(8) NOT NULL
);

CREATE TABLE PISO (
    ID_PISO varchar2(2) PRIMARY KEY,
    DOMICILIO number(8) NOT NULL,
    PORTAL number(8) NOT NULL,
    ESCALERA number(8) NOT NULL,
    PUERTA number(8) NOT NULL,
    ALQUILADO varchar2(1) NOT NULL,
    CONSTRAINT DOMICILIO_F_FK FOREIGN KEY (DOMICILIO)
    REFERENCES EDIFICIO ON DELETE SET NULL
);


CREATE TABLE GARAJE (
    ID_GARAJE varchar2(2) PRIMARY KEY,
    DOMICILIO number(8) NOT NULL,
    PORTAL number(8) NOT NULL,
    PLANTA number(8) NOT NULL,
    N_PLAZA number(8) NOT NULL,
    ALQUILADO varchar2(1) NOT NULL,
    CONSTRAINT DOMICILIO_GF_FK FOREIGN KEY (DOMICILIO)
    REFERENCES EDIFICIO ON DELETE SET NULL
);

CREATE TABLE ALQUILER (
    ID_ALQUILER  number(8) PRIMARY KEY,
    INMUEBLE varchar2(20) NOT NULL,
    INQUILINO number(8) NOT NULL,
    MES date NOT NULL,
    ALQUILER number(8) NOT NULL,
    R_COMUNIDAD number(8) NOT NULL,
    R_AGUA number(8) NOT NULL,
    R_ADMMINISTRADOR number(8) NOT NULL,
    R_LIMPIEZA number(8) NOT NULL,
    CONSTRAINT INQUILINO_FK FOREIGN KEY (INQUILINO) REFERENCES INQUILINO ON DELETE SET NULL
);